modLoader = "javafml"
loaderVersion = "[${forge_version},)"
#issueTrackerURL = ""
license = "MIT License"

[[mods]]
modId = "itemattachments"
version = "${version}"
displayName = "Item Attachments"
authors = "rbasamoyai"
description = """An API and screen utility for simple and immersive item attachments.
Inspired by Unturned and Crayfish's Gun Mod."""
logoFile = "icon.png"

[[dependencies.itemattachments]]
modId = "forge"
mandatory = true
versionRange = "[${forge_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.itemattachments]]
modId = "minecraft"
mandatory = true
versionRange = "${minecraft_version}"
ordering = "NONE"
side = "BOTH"